In [1]:
import numpy as np

In [2]:
# Lists
x = [1, 2, 3]
y = [4, 5, 6, 7]

In [3]:
# List index - Starts with 0 just like Java
print (x[0])
print (x[1])

1
2


In [4]:
# List - start with given index
a_ = np.asarray(y[1:])
print (a_)
print(type(a_))
print(a_.shape)
print(np.array([1,1,1]).shape)

[5 6 7]
<class 'numpy.ndarray'>
(3,)
(3,)


In [5]:
a_ +=  np.array([1,1,1])
print(a_)
print (a_[1])

[6 7 8]
7


In [6]:
# For loop
for i in x:
    print (i)
    
print ('-------')

for j in y:
    print (j)

1
2
3
-------
4
5
6
7


In [7]:
# Zip
x = [1, 2, 3]
y = [4, 5, 6, 7]
for a, b in zip(x, y):
    print (a, b)

1 4
2 5
3 6


In [8]:
# Numpy - zeros
z = np.zeros(5)
print (z)

[ 0.  0.  0.  0.  0.]


In [9]:
# Numpy - when method - np.where returns indices where a given condition is met
print (np.where(np.array([6, 7,8,9, 5, 4, 10]) > 7))

(array([2, 3, 6]),)


In [10]:
p = 1
print(type(p))
q = 1.0
print(type(q))
r = True
print(type(r))

<class 'int'>
<class 'float'>
<class 'bool'>
