Numbers

In [2]:
1

1

In [3]:
1.0

1.0

In [4]:
1 + 1

2

In [5]:
1 + 1.0

2.0

In [6]:
2/2

1

In [8]:
2.0/2

1.0

In [10]:
# Mod
4%3

1

Variables

In [11]:
var = 100

In [13]:
var

100

String

In [16]:
'Hello' + "World"

'HelloWorld'

In [17]:
test_str = 'Mr. {}, Hello!'

In [18]:
test_str.format('Kamal')

'Mr. Kamal, Hello!'

In [19]:
s = '1234567890'

In [20]:
s[0:]

'1234567890'

In [21]:
s[3:]

'4567890'

In [23]:
s[:6]

'123456'

In [24]:
s[1:3]

'23'

List

In [32]:
# Lists
x = [1, 2, 3]
y = [4, 5, 6, 7]

In [33]:
x.append(4)

In [34]:
x

[1, 2, 3, 4]

In [4]:
# List - start with given index
a_ = np.asarray(y[1:])
print (a_)
print(type(a_))
print(a_.shape)
print(np.array([1,1,1]).shape)

[5 6 7]
<class 'numpy.ndarray'>
(3,)
(3,)


In [5]:
a_ +=  np.array([1,1,1])
print(a_)
print (a_[1])

[6 7 8]
7


In [6]:
# For loop
for i in x:
    print (i)
    
print ('-------')

for j in y:
    print (j)

1
2
3
-------
4
5
6
7


In [7]:
# Zip
x = [1, 2, 3]
y = [4, 5, 6, 7]
for a, b in zip(x, y):
    print (a, b)

1 4
2 5
3 6


In [8]:
# Numpy - zeros
z = np.zeros(5)
print (z)

[ 0.  0.  0.  0.  0.]


In [9]:
# Numpy - when method - np.where returns indices where a given condition is met
print (np.where(np.array([6, 7,8,9, 5, 4, 10]) > 7))

(array([2, 3, 6]),)


In [10]:
p = 1
print(type(p))
q = 1.0
print(type(q))
r = True
print(type(r))

<class 'int'>
<class 'float'>
<class 'bool'>


## Dictionary

In [1]:
d = {'key1':'value1','key2':'value2'}

In [2]:
print(d['key1'])

value1


In [5]:
e = {'d1':{'k1':'v1','k2':'v2'}}

In [6]:
print (e['d1']['k2'])

v2


## Boolean

In [7]:
True

True

In [8]:
False

False

## Tuple

In [9]:
t = (1,2,'Hello')

In [10]:
print (t[2])

Hello


## Set

In [13]:
s = {1,2,3,1,2,4}

In [14]:
print (s)

set([1, 2, 3, 4])


In [15]:
s.add('Hello')

In [16]:
s

{1, 2, 3, 4, 'Hello'}

## Comparison Operator

In [17]:
1 > 2

False

In [18]:
1< 2

True

In [19]:
1 == 1

True

In [20]:
1 != 2

True

In [23]:
1 == 1 and 2 == 2

True

In [24]:
1 > 2 or 1 < 2

True

## List Comprehension

In [25]:
a = [1,2,3,4]

In [26]:
b = [num**2 for num in a]

In [27]:
b

[1, 4, 9, 16]

## Functions

In [30]:
def my_func(name):
    print ('Hello {}'.format(name))

In [32]:
my_func('Kamal')

Hello Kamal


In [33]:
def print_message(name='Kamal'):
    print ('Hello {}'.format(name))

In [34]:
print_message()

Hello Kamal


In [35]:
def square(num):
    return num**2

In [36]:
print (square(2))

4


In [38]:
g = [1,2,3,4]
map(square, g)

[1, 4, 9, 16]

## Map & Filter Using Lambda Expr

In [39]:
map(lambda num: num**2, g)

[1, 4, 9, 16]

In [40]:
filter(lambda num: num%2 ==0, g)

[2, 4]

## Numpy

In [1]:
l = [1,2,3,4]

In [3]:
import numpy as np

In [3]:
a = np.array(l)

In [4]:
a

array([1, 2, 3, 4])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [19]:
np.linspace(0,20,9)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ])

In [21]:
# Identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
np.random.rand(5)

array([ 0.66200516,  0.72784422,  0.42661426,  0.02306727,  0.84996627])

In [24]:
np.random.rand(3,3)

array([[ 0.44137919,  0.38896496,  0.87195709],
       [ 0.31759004,  0.17379147,  0.15218299],
       [ 0.14076705,  0.23867491,  0.90839185]])

In [26]:
np.random.randn(5)

array([-0.30852154, -0.04650273, -0.15763432, -1.20208278, -0.1774582 ])

In [27]:
np.random.randn(3,3)

array([[-1.64163841, -0.06667966, -0.06613806],
       [ 1.05142918, -0.34612379,  1.28496181],
       [-0.10480952, -1.29976411, -1.15933417]])

In [32]:
# 5 random integers between 1 and 99
ranarr = np.random.randint(1, 100, 5)

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

65

In [34]:
ranarr.min()

24

In [35]:
ranarr

array([51, 32, 24, 27, 65])

In [36]:
ranarr.argmax()

4

In [37]:
ranarr.argmin()

2

In [38]:
li = [1,2,'Hello']

In [40]:
m = np.array(li)

In [41]:
m.dtype

dtype('S21')

In [42]:
m[0]

'1'

In [43]:
m[2]

'Hello'

## 2D Arrays

In [5]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print (arr2d[2,1])

8


In [11]:
print (arr2d[:3,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [16]:
print (arr2d[:2])

[[1 2 3]
 [4 5 6]]


In [18]:
arr1 = np.arange(50).reshape(5,10)

In [19]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
arr1[1:3,2:4]

array([[12, 13],
       [22, 23]])

### Conditional Selection

In [4]:
arr = np.arange(1,11)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
bool_arr = arr > 4

In [8]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [9]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [15]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10])

## Operations

In [10]:
arr = np.arange(0, 11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [15]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [16]:
# Note 0/0 is Nan
arr / arr

/home/kamal/virtualenvs/mlpy2/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in divide
  from ipykernel import kernelapp as app


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
1 / arr

/home/kamal/virtualenvs/mlpy2/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [20]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [21]:
np.max(arr)

10

In [23]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [24]:
np.log(arr)

/home/kamal/virtualenvs/mlpy2/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])